apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: namespace-policy
policyDefaults:
  namespace: default
  placement:
    labelSelector:
      rhdp_usage: development
  remediationAction: inform
policies:
  - name: create-demo-namespace
    manifests:
      - path: namespace.yaml
